//
//  File.swift
//  
//
//  Created by Stefan Urbanek on 19/09/2023.
//
import PoieticCore

// TODO: Consolidate all the variable/reference types, we have way too many of them


/// Object describing a simulation state variable.
///
/// This is the core detail information of the simulation. There is one
/// state variable for each object, usually a node, that represent a state
/// in the simulation. A stock, a flow or an auxiliary - they all are state
/// variables.
///
public struct ComputedVariable: IndexRepresentable, CustomStringConvertible {
    // TODO: Is not this too fat?
    // TODO: Rename to ComputedVariable, ObjectVariable, NodeVariable
    
    /// ID of the object, usually a node, that represents the variable.
    public let id: ObjectID
    
    /// Index of the variable in the simulation state vector.
    public let index: VariableIndex
    
    /// Type of the computation of the variable.
    public let computation: ComputationalRepresentation
    
    /// Name of the variable.
    public let name: String
    
    public var description: String {
        "var(\(name), id:\(id), idx:\(index))"
    }
}

public struct BoundBuiltinVariable {
    public let builtin: BuiltinVariable
    public let index: VariableIndex
}
public enum SimulationVariableType {
    case computed
    case builtin
}

public enum SimulationVariable {
    case builtin(BoundBuiltinVariable)
    case computed(ComputedVariable)
    
    public var type: SimulationVariableType {
        switch self {
        case .builtin: .builtin
        case .computed: .computed
        }
    }
    
    public var index: VariableIndex {
        switch self {
        case let .builtin(builtin): builtin.index
        case let .computed(computed): computed.index
        }
    }
    
    public var name: String {
        switch self {
        case let .builtin(builtin): builtin.builtin.name
        case let .computed(computed): computed.name
        }
    }
}

/// Structure representing a reference to a simulation variable.
///
/// The structure is analogous to an entry in a symbol table generated by the
/// compiler. It provides information about where a particular simulation
/// variable can be found in the simulation state.
///
public struct BoundVariableReference: Hashable, CustomStringConvertible, TypedValue {
    /// Reference to a variable.
    ///
    public let variable: VariableReference
    
    /// Index in the ``SimulationState`` where the variable value is contained.
    /// For variables representing simulation objects, the index is into the
    /// ``SimulationState//values``, for variables representing built-ins, the
    /// index is into the ``SimulationState//builtins``.
    public let index: Int
    
    /// Type of the wrapped variable.
    ///
    public var valueType: AtomType? { variable.valueType }
    
    public var description: String {
        "(\(index),\(variable))"
    }
}

